#! /bin/bash
# shellcheck disable=SC2207 # Arrays are a pain in bash 3

echo "functions assume they are run from repo root"
echo "run \"list\" for a list of helpers"

### Internal
INIT_LOCATION="$0"

list(){
    ./util/list.awk "$INIT_LOCATION"
}

## External

lint() { 
    ./util/bash_includes/lint
}

start() # Start on localhost:4000
(
    stack setup
    stack build
    stack exec cascadeofinsights clean
    stack exec cascadeofinsights watch
)

stop(){ # kill what is on port 8000
    kill "$(lsof -i :8000 | tail -n 1 | awk '{ print $2 }')" 
}

build() (
    stack setup
    stack build
    stack exec cascadeofinsights build
)
