#! /bin/bash
# shellcheck disable=SC2207 # Arrays are a pain in bash 3

echo "functions assume they are run from repo root"
echo "run \"list\" for a list of helpers"

### Internal
INIT_LOCATION="$0"

list(){
    ./util/list.awk "$INIT_LOCATION"
}

pause(){
   echo "Press enter to continue.  Ctrl-C to bail."
   read -p ""
}

## External

lint() { 
    ./util/bash_includes/lint
}

start() # Start on localhost:4000
(
    stack setup
    stack build
    stack exec cascadeofinsights clean
    stack exec cascadeofinsights watch
)

stop(){ # kill what is on port 8000
    kill "$(lsof -i :8000 | tail -n 1 | awk '{ print $2 }')" 
}

build() (
    stack setup
    stack build
    stack exec cascadeofinsights build
)

publish() {
    echo "All work must be commited in hakyll before running"
    pause
    # clean removes cache
    stack exec cascadeofinsights clean
    rm -rf _site _cache
    git submodule init
    git submodule update
    cd _site
    git pull origin master
    git checkout master
    cd ..
    stack setup
    stack build
    stack exec cascadeofinsights build

    cd _site/
    git add .
    git commit -m "Update [ci skip]"
    git push origin master
    cd ..
    git add _site/
    git add .
    git commit -m "Update [ci skip]"
    git push origin hakyll
}

new_post() {
    date_pattern=$(date "+%Y-%m-%d")-

    echo -n "Post name > "
    read title
    # Convert to ASCII, to lowercase, keep only alphanum and ._- space, and turn spaces into dashes
    clean_title=$(echo "$title" \
        | iconv -f utf8 -t ascii//translit \
        | tr '[:upper:]' '[:lower:]' \
        | tr -dc 'a-z0-9. _-' \
        | tr ' ' '-')

    filename="$date_pattern$clean_title.md"
    author=$(git config --get user.name)

    # Ensure the directory exists before attempting to write the file
    mkdir -p "posts/"

    # Use heredoc correctly to write to the file
    cat > "posts/${filename}" <<EOF
    ---
    title: "$title"
    author: $author
    tags: draft
    ---

    <!--more-->
EOF
}
