#! /bin/bash
# shellcheck disable=SC2207 # Arrays are a pain in bash 3

echo "functions assume they are run from repo root"
echo "run \"list\" for a list of helpers"

### Internal
INIT_LOCATION="$0"


pause(){
   echo "Press enter to continue.  Ctrl-C to bail."
   read -p ""
}

## External

start() # Start on localhost:1313
{
    cd hugo && hugo server -D
}

build() {
    cd hugo && hugo --minify
}
